version: 0.2

env:
  variables:
    S3_BUCKET: "arash-ecs-clf"

phases:

  pre_build: 
    commands:

      # Validate all of the CloudFormation templates
      - chmod a+x ./tests/validate-templates.sh
      - ./tests/validate-templates.sh

  build:
    commands:

      # Sync the templates
      # - aws s3 sync . s3://${S3_BUCKET}

